ALTER TABLE pages
    ADD COLUMN subtitle VARCHAR(255),
    ADD COLUMN layout_type VARCHAR(50) NOT NULL DEFAULT 'STANDARD',
    ADD COLUMN metadata JSONB,
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;