spring.application.name=website

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/website
spring.datasource.username=${DB_USERNAME:website_user}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cap the connection pool size for local development
spring.datasource.hikari.maximum-pool-size=3

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}